
// This file is automatically generated. Do not edit it directly.
/// <reference path="../../types/supabase-profiles.d.ts" />
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojowhfojaswbbuefxaae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qb3doZm9qYXN3YmJ1ZWZ4YWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjIyNzMsImV4cCI6MjA2MzUzODI3M30.NmANqYrXl44nFJNT3yrE2_KhTo7g5qbTb91i7RHKoaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
